/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CopyTextarea: typeof import('./src/components/CopyTextarea.vue')['default']
    InterfaceCheckedBox: typeof import('./src/components/InterfaceCheckedBox.vue')['default']
    SettingDrawer: typeof import('./src/components/SettingDrawer.vue')['default']
    TooltipIcon: typeof import('./src/components/TooltipIcon.vue')['default']
    TypeModal: typeof import('./src/components/TypeModal.vue')['default']
  }
}
